[versions]
gson = "2.13.2"
kotlin_android = "2.2.20"
kotlin_jvm = "2.2.20"
kotlin_reflect = "2.2.20"
kotlin_stdlib = "2.2.20"
kotlin_coroutines = "1.10.2"
shadowjar_ref = "9.2.1"
gplayapi = "0e224071"
org-json = "20250517"
okhttp = "5.1.0"
apache-commonsio = "2.20.0"
apktool-lib = "2.12.0"
classgraph = "4.8.181"
jackson-databind = "2.20.0"
jackson-yaml = "2.20.0"
shizuku-api = "13.1.5"
shizuku-provider = "13.1.5"
rootbeer = "0.1.1"
m3-preferences = "0.2.5"
a_agp = "8.11.1"
a_appcompat = "1.7.1"
a_material = "1.12.0"
a_activity = "1.10.1"
a_constraintlayout = "2.2.1"
a_navigationFragment = "2.9.2"
a_navigationUi = "2.9.2"
a_preference = "1.2.1"
a_workManager = "2.9.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "a_agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_jvm" }
shadowjar = { id = "com.gradleup.shadow", version.ref = "shadowjar_ref" }

[libraries]
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin_stdlib" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin_reflect" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
gplayapi = { group = "com.gitlab.AuroraOSS", name = "gplayapi", version.ref = "gplayapi" }
org-json = { group = "org.json", name = "json", version.ref = "org-json" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
apache-commons-io = { group = "commons-io", name = "commons-io", version.ref = "apache-commonsio" }
apktool_lib = { group = "org.apktool", name = "apktool-lib", version.ref = "apktool-lib" }
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jackson-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson-yaml" }
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku-api" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku-provider" }
rootbeer = { group = "com.scottyab", name = "rootbeer-lib", version.ref = "rootbeer" }
m3-preferences = { group = "com.github.TTTT55", name = "Material-You-Preferences", version.ref = "m3-preferences" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "a_appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "a_material" }
android-activity = { group = "androidx.activity", name = "activity", version.ref = "a_activity" }
android-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "a_constraintlayout" }
android-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "a_navigationFragment" }
android-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "a_navigationUi" }
android-preference = { group = "androidx.preference", name = "preference", version.ref = "a_preference" }
android-work-manager = { group = "androidx.work", name = "work-runtime", version.ref = "a_workManager" }