name: Merge Translations from Crowdin

on:
  repository_dispatch:
    types: [merge_translations]

jobs:
  merge_translations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Create env.properties file
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> env.properties
          echo "CROWDIN_TOKEN=${{ secrets.CROWDIN_API_TOKEN }}" >> env.properties

      - name: Run merge tasks
        run: ./gradlew mergeTranslations

      - name: Update patcher app sources with latest sources
        run: ./gradlew updatePatcherSources

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git reset env.properties
          git commit -m "[general] chore: Update translation sources" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release a new update for patcher-core
        run: ./gradlew :patcher-core:release